version: 2

jobs:
  lint:
    docker:
      - image: singapore/lint-condo
    steps:
      - checkout
      - run:
          name: Linting orbs
          command: yamllint ./orbs
  validate:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run:
          name: Setting up CircleCI CLI
          command: "echo -e \"token: placeholder\nverbose: false > ~/.circleci/cli.yml\""
      - run:
          name: Validating orbs
          command: |
            for ORB in orbs/*; do
              echo "Validating $ORB ..."
              circleci orb validate $ORB
            done

workflows:
  version: 2
  main:
    jobs:
      - lint
      - validate
