version: 2

jobs:
  lint:
    docker:
      - image: singapore/lint-condo
    steps:
      - checkout
      - run:
          name: Linting orbs
          command: yamllint ./orbs

workflows:
  version: 2
  main:
    jobs:
      - lint
